CREATE TABLE CLASSMATES (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

INSERT INTO CLASSMATES VALUES (1, 'Jonh', 17, 'Moscow');
INSERT INTO CLASSMATES VALUES (2, 'Pitter', 31, 'Omsk');
INSERT INTO CLASSMATES VALUES (3, 'Ryan', 30, 'Moscow' );
INSERT INTO CLASSMATES VALUES (4, 'Paola', 18, 'Omsk');
INSERT INTO CLASSMATES VALUES (5, 'Ann', 28, 'London');
INSERT INTO CLASSMATES VALUES (6, 'George', 20, 'Moscow');
INSERT INTO CLASSMATES VALUES (7, 'Lucia', 17, 'York');
INSERT INTO CLASSMATES VALUES (8, 'Gilbert', 51, 'Paris');
INSERT INTO CLASSMATES VALUES (9, 'Frank', 18, 'Moscow');
INSERT INTO CLASSMATES VALUES (10, 'Linsay', 29, 'Oslo');

SELECT * FROM CLASSMATES 
WHERE address = 'Moscow' AND (age < 30 AND age >= 18);
